//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Folder;

export type SiteHero = {
  __typename?: 'SiteHero';
  backgroundImage?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  titleLine3?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SiteBooking = {
  __typename?: 'SiteBooking';
  description?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  phone?: Maybe<Scalars['String']['output']>;
  walkInNotice?: Maybe<Scalars['String']['output']>;
};

export type SiteServices = {
  __typename?: 'SiteServices';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
};

export type SiteStory = {
  __typename?: 'SiteStory';
  mainImage?: Maybe<Scalars['String']['output']>;
  secondaryImage?: Maybe<Scalars['String']['output']>;
  accentImage?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  paragraph1?: Maybe<Scalars['String']['output']>;
  paragraph2?: Maybe<Scalars['String']['output']>;
  signature?: Maybe<Scalars['String']['output']>;
};

export type SitePhilosophy = {
  __typename?: 'SitePhilosophy';
  quote?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
};

export type SiteGallery = {
  __typename?: 'SiteGallery';
  image?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  size?: Maybe<Scalars['String']['output']>;
};

export type SiteContact = {
  __typename?: 'SiteContact';
  backgroundImage?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  mapsUrl?: Maybe<Scalars['String']['output']>;
};

export type SiteFooter = {
  __typename?: 'SiteFooter';
  tagline?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  hero?: Maybe<SiteHero>;
  booking?: Maybe<SiteBooking>;
  services?: Maybe<Array<Maybe<SiteServices>>>;
  story?: Maybe<SiteStory>;
  philosophy?: Maybe<SitePhilosophy>;
  gallery?: Maybe<Array<Maybe<SiteGallery>>>;
  contact?: Maybe<SiteContact>;
  footer?: Maybe<SiteFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteHeroFilter = {
  backgroundImage?: InputMaybe<ImageFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  titleLine3?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteBookingFilter = {
  description?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  walkInNotice?: InputMaybe<StringFilter>;
};

export type SiteServicesFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
};

export type SiteStoryFilter = {
  mainImage?: InputMaybe<ImageFilter>;
  secondaryImage?: InputMaybe<ImageFilter>;
  accentImage?: InputMaybe<ImageFilter>;
  quote?: InputMaybe<StringFilter>;
  paragraph1?: InputMaybe<StringFilter>;
  paragraph2?: InputMaybe<StringFilter>;
  signature?: InputMaybe<StringFilter>;
};

export type SitePhilosophyFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
};

export type SiteGalleryFilter = {
  image?: InputMaybe<ImageFilter>;
  label?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  size?: InputMaybe<StringFilter>;
};

export type SiteContactFilter = {
  backgroundImage?: InputMaybe<ImageFilter>;
  name?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  mapsUrl?: InputMaybe<StringFilter>;
};

export type SiteFooterFilter = {
  tagline?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  hero?: InputMaybe<SiteHeroFilter>;
  booking?: InputMaybe<SiteBookingFilter>;
  services?: InputMaybe<SiteServicesFilter>;
  story?: InputMaybe<SiteStoryFilter>;
  philosophy?: InputMaybe<SitePhilosophyFilter>;
  gallery?: InputMaybe<SiteGalleryFilter>;
  contact?: InputMaybe<SiteContactFilter>;
  footer?: InputMaybe<SiteFooterFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
};

export type SiteHeroMutation = {
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  titleLine3?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBookingMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  phone?: InputMaybe<Scalars['String']['input']>;
  walkInNotice?: InputMaybe<Scalars['String']['input']>;
};

export type SiteServicesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
};

export type SiteStoryMutation = {
  mainImage?: InputMaybe<Scalars['String']['input']>;
  secondaryImage?: InputMaybe<Scalars['String']['input']>;
  accentImage?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  paragraph1?: InputMaybe<Scalars['String']['input']>;
  paragraph2?: InputMaybe<Scalars['String']['input']>;
  signature?: InputMaybe<Scalars['String']['input']>;
};

export type SitePhilosophyMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
};

export type SiteGalleryMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  size?: InputMaybe<Scalars['String']['input']>;
};

export type SiteContactMutation = {
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  mapsUrl?: InputMaybe<Scalars['String']['input']>;
};

export type SiteFooterMutation = {
  tagline?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  hero?: InputMaybe<SiteHeroMutation>;
  booking?: InputMaybe<SiteBookingMutation>;
  services?: InputMaybe<Array<InputMaybe<SiteServicesMutation>>>;
  story?: InputMaybe<SiteStoryMutation>;
  philosophy?: InputMaybe<SitePhilosophyMutation>;
  gallery?: InputMaybe<Array<InputMaybe<SiteGalleryMutation>>>;
  contact?: InputMaybe<SiteContactMutation>;
  footer?: InputMaybe<SiteFooterMutation>;
};

export type SitePartsFragment = { __typename: 'Site', hero?: { __typename: 'SiteHero', backgroundImage?: string | null, titleLine1?: string | null, titleLine2?: string | null, titleLine3?: string | null, description?: string | null } | null, booking?: { __typename: 'SiteBooking', description?: string | null, address?: string | null, hours?: Array<string | null> | null, phone?: string | null, walkInNotice?: string | null } | null, services?: Array<{ __typename: 'SiteServices', name?: string | null, description?: string | null, duration?: string | null, price?: string | null } | null> | null, story?: { __typename: 'SiteStory', mainImage?: string | null, secondaryImage?: string | null, accentImage?: string | null, quote?: string | null, paragraph1?: string | null, paragraph2?: string | null, signature?: string | null } | null, philosophy?: { __typename: 'SitePhilosophy', quote?: string | null, author?: string | null } | null, gallery?: Array<{ __typename: 'SiteGallery', image?: string | null, label?: string | null, tag?: string | null, size?: string | null } | null> | null, contact?: { __typename: 'SiteContact', backgroundImage?: string | null, name?: string | null, address?: string | null, mapsUrl?: string | null } | null, footer?: { __typename: 'SiteFooter', tagline?: string | null, phone?: string | null, email?: string | null, address?: string | null } | null };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', backgroundImage?: string | null, titleLine1?: string | null, titleLine2?: string | null, titleLine3?: string | null, description?: string | null } | null, booking?: { __typename: 'SiteBooking', description?: string | null, address?: string | null, hours?: Array<string | null> | null, phone?: string | null, walkInNotice?: string | null } | null, services?: Array<{ __typename: 'SiteServices', name?: string | null, description?: string | null, duration?: string | null, price?: string | null } | null> | null, story?: { __typename: 'SiteStory', mainImage?: string | null, secondaryImage?: string | null, accentImage?: string | null, quote?: string | null, paragraph1?: string | null, paragraph2?: string | null, signature?: string | null } | null, philosophy?: { __typename: 'SitePhilosophy', quote?: string | null, author?: string | null } | null, gallery?: Array<{ __typename: 'SiteGallery', image?: string | null, label?: string | null, tag?: string | null, size?: string | null } | null> | null, contact?: { __typename: 'SiteContact', backgroundImage?: string | null, name?: string | null, address?: string | null, mapsUrl?: string | null } | null, footer?: { __typename: 'SiteFooter', tagline?: string | null, phone?: string | null, email?: string | null, address?: string | null } | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', backgroundImage?: string | null, titleLine1?: string | null, titleLine2?: string | null, titleLine3?: string | null, description?: string | null } | null, booking?: { __typename: 'SiteBooking', description?: string | null, address?: string | null, hours?: Array<string | null> | null, phone?: string | null, walkInNotice?: string | null } | null, services?: Array<{ __typename: 'SiteServices', name?: string | null, description?: string | null, duration?: string | null, price?: string | null } | null> | null, story?: { __typename: 'SiteStory', mainImage?: string | null, secondaryImage?: string | null, accentImage?: string | null, quote?: string | null, paragraph1?: string | null, paragraph2?: string | null, signature?: string | null } | null, philosophy?: { __typename: 'SitePhilosophy', quote?: string | null, author?: string | null } | null, gallery?: Array<{ __typename: 'SiteGallery', image?: string | null, label?: string | null, tag?: string | null, size?: string | null } | null> | null, contact?: { __typename: 'SiteContact', backgroundImage?: string | null, name?: string | null, address?: string | null, mapsUrl?: string | null } | null, footer?: { __typename: 'SiteFooter', tagline?: string | null, phone?: string | null, email?: string | null, address?: string | null } | null } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  hero {
    __typename
    backgroundImage
    titleLine1
    titleLine2
    titleLine3
    description
  }
  booking {
    __typename
    description
    address
    hours
    phone
    walkInNotice
  }
  services {
    __typename
    name
    description
    duration
    price
  }
  story {
    __typename
    mainImage
    secondaryImage
    accentImage
    quote
    paragraph1
    paragraph2
    signature
  }
  philosophy {
    __typename
    quote
    author
  }
  gallery {
    __typename
    image
    label
    tag
    size
  }
  contact {
    __typename
    backgroundImage
    name
    address
    mapsUrl
  }
  footer {
    __typename
    tagline
    phone
    email
    address
  }
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/160598d4-00c6-4b53-84d8-c1d2db306fc4/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  